db:
  image: postgres
  restart: always
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
kinto:
  restart: always
  build: ./storage
  links:
   - db
  ports:
   - "8888:8888"
  environment:
    KINTO_CACHE_BACKEND: kinto.core.cache.postgresql
    KINTO_CACHE_URL: postgres://postgres:postgres@db/postgres
    KINTO_STORAGE_BACKEND: kinto.core.storage.postgresql
    KINTO_STORAGE_URL: postgres://postgres:postgres@db/postgres
    KINTO_PERMISSION_BACKEND: kinto.core.permission.postgresql
    KINTO_PERMISSION_URL: postgres://postgres:postgres@db/postgres
    KINTO_HTTP_HOST: storage.processeer.io
kinto-web:
  image: nginx
  restart: always
  links:
    - kinto
  environment:
    VIRTUAL_HOST: storage.processeer.io
  volumes:
    - ./storage/conf/nginx.conf:/etc/nginx/nginx.conf:ro
web:
  image: nginx
  restart: always
  environment:
    VIRTUAL_HOST: processeer.io
  volumes:
    - ./client/dist:/usr/share/nginx/html:ro
    - ./client/conf/nginx.conf:/etc/nginx/nginx.conf:ro
