version: "2"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: processeer
      POSTGRES_PASSWORD: aPassword
  kinto:
    build: ./storage
    links:
     - db
    ports:
     - "8888:8888"
    environment:
      KINTO_INI: /code/conf/kinto.ini
      KINTO_CACHE_BACKEND: kinto.core.cache.postgresql
      KINTO_CACHE_URL: postgres://processeer:aPassword@db/postgres
      KINTO_STORAGE_BACKEND: kinto.core.storage.postgresql
      KINTO_STORAGE_URL: postgres://processeer:aPassword@db/postgres
      KINTO_PERMISSION_BACKEND: kinto.core.permission.postgresql
      KINTO_PERMISSION_URL: postgres://processeer:aPassword@db/postgres
