db:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
web:
  image: kinto/kinto-server
  links:
   - db
  ports:
   - "8888:8888"
  environment:
    KINTO_CACHE_BACKEND: kinto.core.cache.postgresql
    KINTO_CACHE_URL: postgres://postgres:postgres@db/postgres
    KINTO_STORAGE_BACKEND: kinto.core.storage.postgresql
    KINTO_STORAGE_URL: postgres://postgres:postgres@db/postgres
    KINTO_PERMISSION_BACKEND: kinto.core.permission.postgresql
    KINTO_PERMISSION_URL: postgres://postgres:postgres@db/postgres
